from __future__ import annotations
from typing import Protocol, Tuple, List

class ITravelModel(Protocol):
    def distance(self, a: Tuple[int,int], b: Tuple[int,int]) -> float: ...
    def travel_time(self, a: Tuple[int,int], b: Tuple[int,int], t0_sec: float, kind: str) -> float: ...
    def route(self, a: Tuple[int,int], b: Tuple[int,int]) -> List[Tuple[int,int]]: ...